# Generated by Django 4.0.4 on 2022-04-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('DOJ', models.DateField(blank=True, null=True)),
                ('Department', models.CharField(blank=True, max_length=50, null=True)),
                ('post', models.CharField(blank=True, max_length=50, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('City', models.CharField(blank=True, max_length=50, null=True)),
                ('Country', models.CharField(blank=True, max_length=50, null=True)),
                ('ZipCode', models.IntegerField(blank=True, null=True)),
                ('State', models.CharField(blank=True, max_length=50, null=True)),
                ('Active', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
